### PR TITLE
Added a button to copy to clipboard the run command

### PR DESCRIPTION
**Pull request by chunkyg**
Now we can just click on a button to copy complete command to run, which earlier we had to select manually.

### CODE REVIEW

**Comment by kkellyy** [comment]
Could you include a picture of the command-to-run box?

**Comment by asottile** [comment]
:( swf

**Comment by kkellyy** [comment]
Only way to copy to clipboard. JS can't do it.

**Comment by asottile** [comment]
I feel like select on click is good enough

**Comment by ymilki** [comment]
Indeed its overkill, but even github compromised on this.

**Comment by kkellyy** [comment]
I think we should actually switch to using the minified version of ZeroClipboard.js

**Comment by kkellyy** [comment]
lg2m

**Comment by chunkyg** [comment]
Replaced with Zeroclipboard.min.js . Snapshots attached :- 

added - stage - clipboard
prod - master - clipboard
stage - prod - clipboard

**Pull request merged**
